INSERT INTO category (name, created_At) VALUES ('Books', now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Feminino', now());
INSERT INTO category (name, created_At) VALUES ('Roupas', now());
INSERT INTO category (name, created_At) VALUES ('Vestidos', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Books', now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Books', now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Books', now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Books', now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Books', now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Books', now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Books', now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Books', now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Books', now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Books', now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Books', now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Books', now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());
INSERT INTO category (name, created_At) VALUES ('Books', now());
INSERT INTO category (name, created_At) VALUES ('Eletronics', now());
INSERT INTO category (name, created_At) VALUES ('Computers',now());